import type { PortfolioProject } from "@/types/content";

export const portfolioProjects: PortfolioProject[] = [
  {
    slug: "urban-bite-restaurant-growth",
    client: "Urban Bite",
    industry: "Restaurants",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=80&auto=format&fit=crop",
    categories: ["Performance Marketing", "WhatsApp Automation"],
    summary: "Grew table bookings 3x for a restaurant chain using Meta Ads and WhatsApp ordering automation.",
    challenge: "Urban Bite struggled with inconsistent footfall and had no digital ordering or booking system.",
    strategy: "We built a WhatsApp-based ordering and reservation flow paired with hyperlocal Meta Ads campaigns.",
    execution: "Launched automated WhatsApp booking bot, ran geo-targeted ad campaigns, and set up retargeting for repeat orders.",
    technologies: ["Meta Ads", "WhatsApp Business API", "GA4"],
    results: [
      { label: "Bookings Growth", value: "3x" },
      { label: "Cost per Lead", value: "-42%" },
      { label: "Repeat Orders", value: "+65%" },
    ],
    testimonial: {
      quote: "ShreeFX transformed how customers discover and book with us. WhatsApp orders alone doubled our weekend revenue.",
      author: "Rohan Mehta",
      role: "Owner, Urban Bite",
    },
    featured: true,
  },
  {
    slug: "carecliniq-healthcare-leads",
    client: "CareCliniq",
    industry: "Healthcare",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1200&q=80&auto=format&fit=crop",
    categories: ["SEO", "Website Development"],
    summary: "Built a new website and local SEO strategy that generated 500+ qualified patient leads in 90 days.",
    challenge: "CareCliniq had an outdated website with poor mobile experience and almost no organic visibility.",
    strategy: "Rebuilt the site on Next.js with local SEO structure and content targeting high-intent patient searches.",
    execution: "Delivered a fast, accessible website, optimized Google Business Profile, and published location-specific content.",
    technologies: ["Next.js", "Local SEO", "Google Business Profile"],
    results: [
      { label: "Organic Leads", value: "500+" },
      { label: "Page Speed Score", value: "98" },
      { label: "Local Ranking", value: "Top 3" },
    ],
    testimonial: {
      quote: "Patient inquiries from our website tripled within three months of launch.",
      author: "Dr. Anjali Shah",
      role: "Director, CareCliniq",
    },
    featured: true,
  },
  {
    slug: "brightlearn-edtech-branding",
    client: "BrightLearn",
    industry: "Education",
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1200&q=80&auto=format&fit=crop",
    categories: ["Branding", "Content Creation"],
    summary: "Complete brand identity and social content system for a growing edtech startup.",
    challenge: "BrightLearn lacked a consistent visual identity across its website, app, and social channels.",
    strategy: "Designed a cohesive brand system and a repeatable content engine for social growth.",
    execution: "Delivered logo, brand guidelines, and a 90-day content calendar with templates for the internal team.",
    technologies: ["Brand Guidelines", "Figma", "Content Calendar"],
    results: [
      { label: "Social Followers", value: "+180%" },
      { label: "Brand Recall", value: "+3.4x" },
      { label: "Engagement Rate", value: "6.8%" },
    ],
    featured: true,
  },
  {
    slug: "primeestate-real-estate-ads",
    client: "PrimeEstate",
    industry: "Real Estate",
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&q=80&auto=format&fit=crop",
    categories: ["Performance Marketing", "AI Automation"],
    summary: "AI-qualified lead pipeline that cut cost-per-qualified-lead by 38% for a real estate developer.",
    challenge: "High volume of unqualified leads from broad ad targeting was overwhelming the sales team.",
    strategy: "Combined Meta and Google Ads with an AI chatbot to automatically qualify budget and intent before handoff.",
    execution: "Built qualification chatbot, refined ad targeting, and integrated leads directly into the sales CRM.",
    technologies: ["Google Ads", "Meta Ads", "AI Chatbot", "CRM Integration"],
    results: [
      { label: "Qualified Leads", value: "+120%" },
      { label: "Cost per Qualified Lead", value: "-38%" },
      { label: "Sales Response Time", value: "<5 min" },
    ],
    featured: true,
  },
  {
    slug: "styloom-dtoc-ecommerce",
    client: "Styloom",
    industry: "E-commerce",
    image: "https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=1200&q=80&auto=format&fit=crop",
    categories: ["Performance Marketing", "Video Editing"],
    summary: "Scaled a D2C fashion brand's Meta Ads revenue by 4x with creative testing and video content.",
    challenge: "Styloom's static ad creatives had plateaued and ROAS was declining month over month.",
    strategy: "Introduced a rapid video creative testing framework paired with dynamic retargeting.",
    execution: "Produced 40+ short-form video ads, tested hooks weekly, and scaled winning creatives across campaigns.",
    technologies: ["Meta Ads", "Video Editing", "Dynamic Retargeting"],
    results: [
      { label: "Revenue Growth", value: "4x" },
      { label: "ROAS", value: "6.2x" },
      { label: "Video CTR", value: "+58%" },
    ],
  },
  {
    slug: "buildright-manufacturing-website",
    client: "BuildRight Industries",
    industry: "Manufacturing",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1200&q=80&auto=format&fit=crop",
    categories: ["Website Development", "SEO"],
    summary: "A B2B catalog website and SEO strategy that generated consistent inbound enquiries.",
    challenge: "BuildRight relied entirely on offline referrals and had no digital presence for B2B buyers.",
    strategy: "Built a product catalog website with SEO-optimized category pages targeting procurement searches.",
    execution: "Launched Next.js website with structured data, technical SEO, and gated spec-sheet downloads.",
    technologies: ["Next.js", "Technical SEO", "Structured Data"],
    results: [
      { label: "Inbound Enquiries", value: "+90/mo" },
      { label: "Organic Traffic", value: "+240%" },
      { label: "Bounce Rate", value: "-31%" },
    ],
  },
];

export const portfolioCategories = [
  "Website Development",
  "Branding",
  "Performance Marketing",
  "WhatsApp Automation",
  "SEO",
  "Content Creation",
  "Video Editing",
  "AI Automation",
] as const;

export function getPortfolioProjectBySlug(slug: string) {
  return portfolioProjects.find((project) => project.slug === slug);
}
